version: '3'

services:
  gpt4free:
    image: hlohaus789/g4f:latest
    shm_size: 1gb
    environment:
      G4F_NO_GUI: "1"
      G4F_VERSION: "0.2.0.3"
    volumes:
      - .:/app
    ports:
      - '8080:8080'
      - '1337:1337'
      - '7900:7900'